[tool.poetry]
name = "uttc-ai-curriculum"
version = "0.1.0"
description = ""
authors = ["Haruki Momiyama GV <momiyama@growth-verse.ai>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
numpy = "^2.2.3"
pandas = "^2.2.3"
scikit-learn = "^1.6.1"
xgboost = "^2.1.4"
lightgbm = "^4.6.0"
llama-index = "^0.12.22"
langchain-core = "^0.3.41"
langchain = "^0.3.20"
openai = "^1.65.4"
fastapi = "^0.115.11"
uvicorn = "^0.34.0"
pymysql = "^1.1.1"
cloud-sql-python-connector = "^1.17.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
